home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^user_index', views.user_index, name='user_index'),
    url(r'^user_info', views.user_info, name='user_info'),

    url(r'^login', views.login, name='login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^admin_login', views.admin_login, name='admin_login'),
    url(r'^register', views.register, name='register'),

    url(r'^user_list', views.user_list, name='user_list'),
    url(r'^user_detail/(?P<s_no>\d+)/$', views.user_detail, name='user_detail'),
    url(r'^reset_pwd/(?P<s_no>\d+)/$', views.reset_pwd, name='reset_pwd'),
    url(r'^account_normal/(?P<s_no>\d+)/$', views.account_normal, name='account_normal'),
    url(r'^account_unnormal/(?P<s_no>\d+)/$', views.account_unnormal, name='account_unnormal'),
    url(r'^delete_user', views.delete_user, name='delete_user'),
    url(r'^update_user', views.update_user, name='update_user'),

    url(r'^book_list', views.book_list, name='book_list'),
    url(r'^book_history', views.book_history, name='book_history'),
    url(r'^borrow_list', views.borrow_list, name='borrow_list'),
    url(r'^user_book_list', views.user_book_list, name='user_book_list'),
    url(r'^send_email', views.send_email, name='send_email'),
    url(r'^notify_user', views.notify_user, name='notify_user'),
    url(r'^refuse_user', views.refuse_user, name='refuse_user'),
    url(r'^user_apply_list', views.user_apply_list, name='user_apply_list'),
    url(r'^cancel_apply/(?P<id>\d+)/$', views.cancel_apply, name='cancel_apply'),
    url(r'^alter_apply_status/(?P<id>\d+)/$', views.alter_apply_status, name='alter_apply_status'),
    url(r'^purchase', views.purchase, name='purchase'),
    url(r'^user_borrow/(?P<book_id>\d+)/$', views.user_borrow, name='user_borrow'),
    url(r'^add_book', views.add_book, name='add_book'),
    url(r'^add_apply', views.add_apply, name='add_apply'),
    url(r'^book_detail/(?P<binumber>\d+)/$', views.book_detail, name='book_detail'),
    url(r'^borrow_book/(?P<book_id>\d+)/$', views.borrow_book, name='borrow_book'),
    url(r'^delay_book/(?P<book_id>\d+)/$', views.delay_book, name='delay_book'),
    url(r'^back_book/(?P<borrow_id>\d+)/$', views.back_book, name='back_book'),
    url(r'^modify_book/(?P<binumber>\d+)/$', views.modify_book, name='modify_book'),

    url(r'^category_list', views.category_list, name='category_list'),
    url(r'^add_category', views.add_category, name='add_category'),
    url(r'^del_category/(?P<id>\d+)/$', views.del_category, name='del_category'),
    url(r'^alter_category/(?P<id>\d+)/$', views.alter_category, name='alter_category'),

    url(r'^notice_list', views.notice_list, name='notice_list'),
    url(r'^user_notice', views.user_notice, name='user_notice'),
    url(r'^notice_detail/(?P<id>\d+)/$', views.notice_detail, name='notice_detail'),
    url(r'^add_notice', views.add_notice, name='add_notice'),
    url(r'^delete_notice/(?P<id>\d+)/$', views.delete_notice, name='delete_notice'),
]

wenhua_library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^wenhua/',include('home.urls'))
]

home/forms.py
from django import forms
from home import models

#用户登录表单验证
class UserLoginForm(forms.Form):
    username = forms.CharField(min_length=2,label="用户名",max_length=20,widget=forms.TextInput(attrs={'class':'form-control form-control-lg','placeholder':'学号'}))
    pwd = forms.CharField(min_length=6,max_length=20,label="密码",widget=forms.PasswordInput(attrs={'class':'form-control form-control-lg','placeholder':'密码'}))

    def clean(self):
        username = self.cleaned_data['username']
        pwd = self.cleaned_data['pwd']
        verify_user = models.student_user.objects.filter(s_no=username, s_pwd=pwd,s_status=1)
        if not verify_user:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = username
        return self.cleaned_data


#管理员登录表单验证
class AdminLoginForm(forms.Form):
    username = forms.CharField(min_length=2,label="用户名",max_length=20,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'工作号'}))
    pwd = forms.CharField(min_length=2,max_length=20,label="密码",widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'密码'}))

    def clean(self):
        username = self.cleaned_data['username']
        pwd = self.cleaned_data['pwd']
        verify_user = models.admin_user.objects.filter(as_work_id=username, as_password=pwd,as_status=1)
        if not verify_user:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = username
        return self.cleaned_data

#用户注册表单验证
class RegisterForm(forms.Form):
    username = forms.CharField(min_length=2,label="学号",max_length=20,widget=forms.TextInput(attrs={'class':'form-control'}))
    s_name = forms.CharField(min_length=2,max_length=20,label="姓名",widget=forms.TextInput(attrs={'class':'form-control'}))
    s_xi = forms.CharField(min_length=2,max_length=20,label="院系",widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(min_length=2,max_length=20,label="密码",widget=forms.TextInput(attrs={'class':'form-control'}))
    password_again = forms.CharField(min_length=2,max_length=20,label="确认密码",widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.CharField(min_length=2,max_length=20,label="邮箱",widget=forms.EmailInput(attrs={'class':'form-control'}))
    s_sex = forms.ChoiceField(label="性别",choices=((0,'男'),(1,'女')))

    def clean_username(self):
        username = self.cleaned_data['username']
        verify_user = models.student_user.objects.filter(s_no=username,s_status=1)
        if verify_user:
            raise forms.ValidationError("该学号已被注册过")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        verify_user = models.student_user.objects.filter(s_email=email,s_status=1)
        if verify_user:
            raise forms.ValidationError("该邮箱已被注册过")
        return email

    def clean_password(self):
        password = self.data.get('password')
        password_again = self.data.get('password_again')
        if password != password_again:
            raise forms.ValidationError('两次输入密码不一致')
        return password_again

#公告栏添加表单验证
class NoticeForm(forms.Form):
    title = forms.CharField(min_length=2, label="公告栏标题", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(min_length=2, label="公告栏内容", max_length=2000, widget=forms.Textarea(attrs={'class': 'form-control'}))

    def clean_title(self):
        title = self.data.get('title')
        verify_title = models.notice_man.objects.filter(nm_title=title)
        if verify_title:
            raise forms.ValidationError('该公告栏已存在')
        return title

    def clean_content(self):
        content = self.data.get('content')
        verify_content = models.notice_man.objects.filter(nm_content=content)
        if verify_content:
            raise forms.ValidationError('该内容已存在')
        return content

#图书分类表单验证
class CategoryForm(forms.Form):
    id = forms.IntegerField(label="图书类别id", min_value=1,max_value=100000, widget=forms.TextInput(attrs={'class': 'form-control'}))
    name = forms.CharField(min_length=2, label="图书类别名称", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_name(self):
        name = self.data.get('name')
        verify_name = models.book_category.objects.filter(bc_info=name)
        if verify_name:
            raise forms.ValidationError('已存在该图书分类')
        return name

    def clean_id(self):
        id = self.data.get('id')
        verify_id = models.book_category.objects.filter(bc_id=id)
        if verify_id:
            raise forms.ValidationError('已存在该图书分类id')
        return id

#图书新增表单验证
class AddBookForm(forms.Form):
    book_id = forms.CharField(label="图书编号", min_length=2,max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_name = forms.CharField(min_length=2, label="图书名称", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_publish = forms.CharField(min_length=2, label="出版社名称", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_price = forms.FloatField( label="图书价格", widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_author = forms.CharField(label="作者", widget=forms.TextInput(attrs={'class': 'form-control'}),min_length=1,max_length=30)
    book_publish_date = forms.DateField(label="出版日期", widget=forms.DateInput(attrs={'class': 'form-control','type':'date'}))
    book_sn = forms.CharField(label="SN号", widget=forms.TextInput(attrs={'class': 'form-control'}),min_length=1,max_length=30)
    book_work_id = forms.CharField(label="书架编号", widget=forms.TextInput(attrs={'class': 'form-control'}),required=False,min_length=1,max_length=30)
    book_category = forms.ModelChoiceField(queryset=models.book_category.objects.all(),empty_label="请选择类别",label="图书分类")

    def clean_book_id(self):
        book_id = self.data.get('book_id')
        verify_id = models.book_info.objects.filter(bi_number=book_id)
        if verify_id:
            raise forms.ValidationError('图书编号已存在')
        return book_id

    def clean_book_work_id(self):
        book_work_id = self.data.get('book_work_id')
        verify_work = models.book_info.objects.filter(bi_caseid=book_work_id)
        if verify_work:
            raise forms.ValidationError("该书架已放置了图书，请选择其他的书架")
        return book_work_id


#图书新增表单验证
class AlterBookForm(forms.Form):
    book_id = forms.CharField(label="图书编号", min_length=2,max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}),required=False)
    book_name = forms.CharField(min_length=2, label="图书名称", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_publish = forms.CharField(min_length=2, label="出版社名称", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_price = forms.FloatField( label="图书价格", widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_author = forms.CharField(label="作者", widget=forms.TextInput(attrs={'class': 'form-control'}),min_length=1,max_length=30)
    book_sn = forms.CharField(label="SN号", widget=forms.TextInput(attrs={'class': 'form-control'}),min_length=1,max_length=30)
    book_work_id = forms.CharField(label="书架编号", widget=forms.TextInput(attrs={'class': 'form-control'}),required=False,min_length=1,max_length=30)

    def clean_book_id(self):
        book_id = self.data.get('book_id')
        verify_id = models.book_info.objects.filter(bi_number=book_id)
        if verify_id:
            raise forms.ValidationError('图书编号已存在')
        return book_id

    def clean_book_work_id(self):
        book_work_id = self.data.get('book_work_id')
        verify_work = models.book_info.objects.filter(bi_caseid=book_work_id)
        if verify_work:
            raise forms.ValidationError("该书架已放置了图书，请选择其他的书架")
        return book_work_id

#图书申请表单
class ApplyBookForm(forms.Form):
    book_id = forms.CharField(label="图书名称", min_length=2,max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_name = forms.CharField(min_length=2, label="图书作者", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_publish = forms.CharField(min_length=2, label="出版社名称", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    book_price = forms.FloatField( label="图书价格", widget=forms.TextInput(attrs={'class': 'form-control'}))

templates/add_apply.html
{% extends 'base.html' %}
{% block title %}申请图书{% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/base.js"></script>
<div class="main">
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                    {{apply_book_form}}
                    <input type="submit" value="确认申请" class="btn btn-primary pull-right">
                </form>
                  </div>
                </div>
            </div>
        </div>
        </div>
</div>
{% endblock %}

templates/add_book.html
{% extends 'base.html' %}
{% block title %}新增图书{% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/base.js"></script>
<div class="main">
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                    {{add_book_form}}
                    <input type="submit" value="确定" class="btn btn-primary pull-right">
                </form>
                  </div>
                </div>
            </div>
        </div>
        </div>
</div>
<br>
<br>
<br>
{% endblock %}

templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文华借阅系统管理员登录</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body style="background-color:LightSkyBlue">
<div class="main">
    <div class="containter">
                <h1>文华学院图书馆信息系统</h1>
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">管理员登录</h3>
                  </div>
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                    {{ admin_login_form }}
                    <input type="submit" value="登录" class="btn btn-primary pull-right">
                </form>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/alter_book.html
{% extends 'base.html' %}
{% block title %}修改图书{% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/base.js"></script>
<div class="main">
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                        <label for="id_id">图书编号:</label>
                        <input type="text" value="{{ id}}" name="book_id" class="form-control" disabled="disabled">
                        <label for="id_name">图书名称:</label>
                        <input type="text" value=" {{ bi_name }}" name="book_name" class="form-control" required_id="id_book_name">
                        <label for="id_name">出版社名称:</label>
                        <input type="text" value=" {{ bi_publish_name }}" name="book_publish" class="form-control" required_id="id_book_publish">
                        <label for="id_name">图书价格:</label>
                        <input type="text" value=" {{ bi_price }}" name="book_price" class="form-control" required_id="id_book_price">
                        <label for="id_name">作者:</label>
                        <input type="text" value=" {{ bi_author }}" name="book_author" class="form-control" required_id="id_book_author">
                        <label for="id_name">SN号:</label>
                        <input type="text" value=" {{ bi_sn_number }}" name="book_sn" class="form-control" required_id="id_book_sn">
<!--                        <label for="id_name">图书状态:</label>-->
<!--                        <input type="text" value=" {{ bi_status }}" name="book_status" class="form-control" required_id="id_book_status">-->

                        <label for="id_name">书架编号:</label>
                        <input type="text" value=" {{ bi_caseid }}" name="book_work_id" class="form-control" required_id="id_book_work_id">
                        <label for="id_name">当前是否在馆:</label>
                        <select id="book_state" name="book_state">
                            <option value="1">在馆</option>
                            <option value="0">不在馆</option>
                        </select>
                        <label for="id_name">图书状态:</label>
                        <select id="bi_status" name="bi_status">
                            <option value="1">正常</option>
                            <option value="2">损坏</option>
                        </select>
<!--                        <label for="id_name">当前是否在馆:</label>-->
<!--                        <input type="text" value=" {{ title }}" name="book_state" class="form-control" required_id="id_book_state">-->
                    <input type="submit" value="确定" class="btn btn-primary pull-right">
                </form>
                  </div>
                </div>
            </div>
        </div>
        </div>
</div>
<br>
<br>
<br>
{% endblock %}

templates/book_detail.html
{% extends 'base.html' %}
{% block title %}图书详情{% endblock %}
{% block content %}
{%if book_detail %}
<div>
    <div class="panel panel-default">
  <div class="panel-heading">图书详情</div>
  <table class="table">
      {% for row in book_detail%}
      <tr><td>图书编号:{{row.bi_number}}</td></tr>
      <tr><td>图书名称:{{row.bi_name}}</td></tr>
      <tr><td>出版社名称:{{row.bi_publish_name}}</td></tr>
      <tr><td>图书价格:{{row.bi_price}}</td></tr>
      <tr><td>作者:{{row.bi_author}}</td></tr>
      <tr><td>类别:{{row.bi_category}}</td></tr>
      <tr><td>SN号:{{row.bi_sn_number}}</td></tr>
      <tr><td>图书状态:{{row.bi_status}}</td></tr>
      <tr><td>书架编号:{{row.bi_caseid}}</td></tr>
      <tr><td>当前是否在馆:{{row.bi_state}}</td></tr>
      <tr><td>入馆时间:{{row.bi_time_created}}</td></tr>
      <tr><td>出版日期:{{row.bi_publish_date}}</td></tr>
      {%endfor%}

  </table>
</div>
</div>
{% else %}
<p>暂无数据</p>
{%endif%}
{% endblock %}

templates/book_history.html
{% extends 'user_base.html' %}
{% block title %}借阅记录{% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/base.js"></script>
<!--<div class="search">-->
<!--    <form method="GET">-->
<!--        <div class="form-inline row">-->
<!--          <input type="text" class="form-control" placeholder="请输入姓名或学号查询" maxlength="50" name="search_keys"/>-->
<!--          <button class="btn btn-primary">搜 索</button>-->
<!--        </div>-->
<!--    </form>-->
<!--</div>-->
<div class="search_content">
<div class="panel panel-default">
  <div class="panel-heading">借阅信息</div>
          {%if history%}
  <table class="table">
    <th>图书编号</th>
    <th>书名</th>
    <th>借书日期</th>
    <th>应还日期</th>
    <th>借书状态</th>
    <th>操作</th>

        {% for row in history %}
        <tr>
            <td>
                {{ row.bb_number }}
            </td>
            <td>
                {{ row.book_name }}
            </td>
            <td>
                {{ row.bb_borrow_date }}
            </td>
            <td>
                {{ row.bb_back_date }}
            </td>
            <td>
                {{ row.bb_state }}
            </td>
            <td>
                {% if row.frequency == 0 and row.bb_state == '借阅中' %}
                <a href={% url "delay_book" row.id %}>续借</a>
                {%else%}
                {%endif%}
            </td>
        </tr>
        {% endfor %}
{% else %}
<p style="margin-left:30px;">暂无借阅记录</p>
{%endif%}
  </table>
</div>
</div>
{% endblock %}

templates/book_list.html
{% extends 'base.html' %}
{% block title %}图书管理{% endblock %}
{% block content %}
<div class="search">
    <form method="GET">
        <div class="form-inline row">
          <input type="text" class="form-control" placeholder="请输入书名或图书编号" maxlength="50" name="search_keys"/>
          <button class="btn btn-primary">搜 索</button>
        </div>
    </form>
</div>

<div class="search_content">
    <a class="btn btn-primary" href={% url 'add_book'%}>新增图书</a>
<div class="panel panel-default">
  <div class="panel-heading">图书基本信息</div>
      {%if book_list%}
  <table class="table">
    <th>图书编号</th>
    <th>SN号</th>
    <th>图书名称</th>
    <th>出版社</th>
    <th>是否在馆</th>
    <th>是否损坏</th>
    <th>操作</th>

        {% for row in book_list %}
        <tr>
            <td>
                {{ row.bi_number }}
            </td>
            <td>
                {{ row.bi_sn_number }}
            </td>
            <td>
                {{ row.bi_name }}
            </td>
            <td>
                {{ row.bi_publish_name }}
            </td>
            <td>
                {{ row.bi_state }}
            </td>
            <td>
                {{ row.bi_status }}
            </td>
            <td>
                <a href={%url 'book_detail' row.bi_number%}>查看</a>
                <a href={%url "modify_book" row.bi_number%}>修改</a>
            </td>
        </tr>
        {% endfor %}
{% else %}
<p style="margin-left:30px;">暂无图书</p>
{%endif%}
  </table>
</div>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文华借阅系统学生登录</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body style="background-color:LightSkyBlue">
<div class="main">
    <div class="containter">
        <h1>文华学院图书馆信息系统</h1>
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">读者登录</h3>
                  </div>
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                    {{login_form}}
                    <input type="submit" value="登录" class="btn btn-primary pull-right">
                </form>
                  </div>
                </div>
            </div>
        </div>
        </div>
    <a href={% url "register" %}>去注册>></a><br>
<a href={% url "admin_login" %}>管理员登录>></a>
</div>
</body>
</html>

templates/update_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改用户信息</title>
</head>
<body>
<form method="POST" action="">
    {%csrf_token%}
    <input type="text" placeholder="所在院系" name="s_xi"><br>
    <input type="text" placeholder="新密码" name="s_password"><br>
    <input type="text" placeholder="确认密码" name="s_confirm_password"><br>
    <input type="text" placeholder="邮箱" name="s_email"><br>
    <input type="submit">
</form>
</body>
</html>

templates/user_info.html
{% extends 'user_base.html' %}
{% block title %}资料修改{% endblock %}
{% block content %}
<script type="text/javascript" src="/static/js/base.js"></script>
<div class="main">
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 cos-xs-offset-4">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <form method="POST" action="">
                    {%csrf_token%}
                        <label for="id_id">学号:</label>
                        <input type="text" value="{{ user_name }}" name="username" class="form-control" disabled="disabled">
                        <label for="id_name">姓名:</label>
                        <input type="text" value=" {{ user_display }}" name="display_name" class="form-control" required_id="id_book_name" disabled="disabled">
                        <label for="id_name">借书数量:</label>
                        <input type="text" value="0" name="book_publish" class="form-control" required_id="id_book_publish" disabled="disabled">
                        <label for="id_name">院系:</label>
                        <input type="text" value=" {{ xi }}" name="xi" class="form-control" required_id="id_book_price">
                        <label for="id_name">邮箱:</label>
                        <input type="text" value=" {{ email }}" name="email" class="form-control" required_id="id_book_author">
                        <label for="id_name">联系电话:</label>
                        <input type="text" value=" {{ mobile }}" name="mobile" class="form-control" required_id="id_book_sn">
                        <label for="id_name">注册时间:</label>
                        <input type="text" value=" {{ register_time }}" name="regirster" class="form-control" required_id="id_book_work_id" disabled="disabled">
                        <label for="id_name">性别:</label>
                        <select id="sex" name="sex">
                            <option value="0">男</option>
                            <option value="1">女</option>
                        </select>
                    <input type="submit" value="修改" class="btn btn-primary pull-right">
                </form>
                  </div>
        </div>
        </div>
</div>
<br>
<br>
<br>
{% endblock %}